# Generated by Django 2.1.3 on 2018-11-03 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='guest_amount',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
