# Generated by Django 2.1.3 on 2018-11-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20181103_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['check_in']},
        ),
    ]
