# Generated by Django 2.1.3 on 2018-11-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20181104_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingimage',
            name='image',
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_url',
            field=models.URLField(default='https://res.cloudinary.com/dc6juzjbb/image/upload/v1541326775/hz0taajm40dmn3osme8m.png'),
            preserve_default=False,
        ),
    ]
