# Generated by Django 2.1.3 on 2018-11-04 10:33

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20181104_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(default=1, upload_to=listings.models.listing_image_directory_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
