# Generated by Django 2.1.3 on 2018-11-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_remove_listingimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
